apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: codefresh
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://otwld.github.io/ollama-helm
    targetRevision: 1.0.4
    chart: ollama
    helm:
      releaseName: ollama
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true