version: '1.0'
triggers:
  - event: push.heads
    branch:
      - main
    workflow: ollama-helm-pipeline
  - event: pull_request.opened
    workflow: ollama-helm-pipeline
  - event: pull_request.synchronize
    workflow: ollama-helm-pipeline